target 'DSNestedAccordion', :exclusive => true do
  pod "DSNestedAccordion", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DSNestedAccordion", :path => "../"
  pod 'Kiwi/XCTest', "~> 2.2.4"
end
